Repository airscripts/awesome-steam-deck, pull requests merged in 2023-10, with the labels that each got.

#32 feat(ci): add linker.yml
  .github/workflows/linker.yml
Labels: feature

#33 feat(ci): add linter also on push
  .github/workflows/linter.yml
Labels: feature

#34 refactor(ci): change interaction-checker job name
  .github/workflows/interaction.yml
Labels: enhancement

#37 feat: add accessories
  README.md
Labels: feature

#38 feat: add various links
  README.md
Labels: feature, hacktoberfest-accepted
